### ISSUE TITLE
Regarding Randomness

### ISSUE THREAD

**Issue by wyhsleep** [bowang-lab/U-Mamba#10]
Hello,

Your work is very interesting and I have a question about the code that I'd like to discuss with you. Despite fixing all the random seeds, I'm still observing randomness in the results of my runs. Have you encountered this kind of issue before?

**Comment by JunMa11** [comment]
Hi @wyhsleep ,

Thanks for sharing this point. We didn't run the same model multiple times. Could you please share how the results vary in different training runs?
