### ISSUE TITLE
mamba变异? 在Cells in Microscopy上跑出的DICE比论文里报的高三十多个点. 请问是我哪里处理错了嘛？

### ISSUE THREAD

**Issue by XGGNet** [bowang-lab/U-Mamba#12]
性能图 和 training log 附上

![image](https://github.com/bowang-lab/U-Mamba/assets/58136000/450d968f-2573-4c88-9d77-a255bafa8c8b)

![image](https://github.com/bowang-lab/U-Mamba/assets/58136000/91366512-b599-45a2-a901-4efe00c653aa)

[training_log_2024_1_19_18_55_04.txt](https://github.com/bowang-lab/U-Mamba/files/14008093/training_log_2024_1_19_18_55_04.txt)

`

**Comment by JunMa11** [comment]
Hi @XGGNet ，

Thanks for your interest. 

As we mentioned in the paper, cell segmentation is an instance segmentation task. We should use f1 rather the dice. Here is the script to compute the metric. 

https://github.com/bowang-lab/U-Mamba/blob/main/evaluation/compute_cell_metric.py
