### ISSUE TITLE
How to do model inference and obtain the results in the paper

### ISSUE THREAD

**Issue by TicTacToePP** [bowang-lab/U-Mamba#13]
As the output folder only contains fold_all, I add a -f all after the provided inference command.

The command used for testing:
`nnUNetv2_predict -i ./data/nnUNet_results/Dataset704_Endovis17 -o ./test_endo -d 704 -c 2d -tr nnUNetTrainerUMambaBot --disable_tta -f all`

The results:
![image](https://github.com/bowang-lab/U-Mamba/assets/106510995/b2ec8061-697b-46af-9635-0cb87d6e7d7f)

**Comment by TicTacToePP** [comment]
I managed to solve by myself to successfully get the results. 

However, I am still confused by the standard deviation in the table. How to obtain them and why they have so large values?

![image](https://github.com/bowang-lab/U-Mamba/assets/106510995/ceaed68f-cd8e-4fcd-a88b-4b1978af80aa)

**Comment by JunMa11** [comment]
Hi @TicTacToePP ,

Thanks for your interest.

Did you try the evaluation code?

https://github.com/bowang-lab/U-Mamba/tree/main/evaluation

**Comment by TicTacToePP** [comment]
Hi @JunMa11,

Thanks for your response. Yes, I obtained the results with the evaluation code. 
But I am wondering how to get the std values (after ±) in the table.

**Comment by ff98li** [comment]
Hi @TicTacToePP ,
The evaluation scripts generate CSV files containing the computed metric for each test case. The mean and standard deviation reported in our tables are calculated across all these test cases from the generated CSV files. For abdomen datasets with metric values of multiple organ classes reported in the CSV files, you can first calculate the average metric across classes for each case, and then calculate the standard deviation and mean across all test cases to obtain the reported means and standard deviations.

**Comment by shenggebiya** [comment]
> 由于输出文件夹仅包含fold_all，因此我在提供的推理命令后添加了 -f all。
> 
> 用于测试的命令： `nnUNetv2_predict -i ./data/nnUNet_results/Dataset704_Endovis17 -o ./test_endo -d 704 -c 2d -tr nnUNetTrainerUMambaBot --disable_tta -f all`
> 
> 结果： ![image](https://private-user-images.githubusercontent.com/106510995/298801762-b2ec8061-697b-46af-9635-0cb87d6e7d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTYzMTAsIm5iZiI6MTcwODI1NjAxMCwicGF0aCI6Ii8xMDY1MTA5OTUvMjk4ODAxNzYyLWIyZWM4MDYxLTY5N2ItNDZhZi05NjM1LTBjYjg3ZDZlN2Q3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTMzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWIxMDhhNzNmOGIzYjllOWQzNTQyMzM2MGNhYTQ3NGRkNjJkMTk2NjYzMDBhNDM5MzBjMmI3NTg5MDc0YjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KlWuhUdbicaj3RwhYaapFJJg7D4XWESUmNrqAYZQ1Uc)

Excuse me, how did you solve this problem
