### ISSUE TITLE
median_image_size_in_voxels

### ISSUE THREAD

**Issue by Saul62** [bowang-lab/U-Mamba#17]
Your 'median_image_size_in_voxels' field now has a value of [96, 310,310], right?
I want to change the value of the 'median_image_size_in_voxels' field in 3D lowres U-Net configuration to [96, 96, 96]. Where can I modify it?
I can't find a file in the nnUNetv2 framework that stores configuration information, such as nnUNetPlans.json.

**Comment by JunMa11** [comment]
hi @Saul62 ，

After running the preprocessing, the plan file will be available on the pre-processing folder
