### ISSUE TITLE
How do I  Get results on a test dataset

### ISSUE THREAD

**Issue by shenggebiya** [bowang-lab/U-Mamba#19]
![image](https://github.com/bowang-lab/U-Mamba/assets/42925030/c353867d-41ea-47ee-9596-33cb73babcb0)

![image](https://github.com/bowang-lab/U-Mamba/assets/42925030/664bb110-b48c-40cc-8aa4-d86a30438080)

When I run the evaluation script, this is clearly the result of the training set
![image](https://github.com/bowang-lab/U-Mamba/assets/42925030/13c7d805-e845-40cb-b6d4-df33b21eb7f1)

**Comment by beasthunter758** [comment]
Hi, How did you manage to run the evaluation script?

**Comment by sxqhyc** [comment]
Hello, I also have the same confusion, how to perform indicator evaluation on val data set, how did you solve this problem
