### ISSUE TITLE
the error of "pip install -e . "

### ISSUE THREAD

**Issue by 2265103334** [bowang-lab/U-Mamba#20]
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/batchgenerators/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/batchgenerators/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/batchgenerators/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/batchgenerators/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/batchgenerators/
ERROR: Could not find a version that satisfies the requirement argparse (from unittest2) (from versions: none)                                                                ERROR: No matching distribution found for argparse

**Comment by MARO848** [comment]
did you solve this error

**Comment by JunMa11** [comment]
It is the network issue. 

Please make sure that the workstation can access networks to download the packages.
