### ISSUE TITLE
Argument passed to at() was not in the map.

### ISSUE THREAD

**Issue by Overflowu7** [bowang-lab/U-Mamba#22]
I'm having problems replacing Umaba's encoder and decoder with nnUNet's original decoder:

Argument passed to at() was not in the map.

And when this problem occurs, the pseudo-loss stays at 0.
Have you seen this problem before? Looking forward to your reply!

**Comment by JunMa11** [comment]
Hi @Overflowu7 ,

sorry for the late reply. We didn't try this. Could you please share more details?

**Comment by Overflowu7** [comment]
thanks you for your reply! I will give the infomation. But this is a warning, not an error.
Epoch 0
Current learning rate: 0.01
using pin_memory on device 1
/home/wu/wyc/nnUNet/nnunetv2/net/mamba/UMambaEnc.py:46: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert C == self.dim
/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/einops/einops.py:316: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  known: Set[str] = {axis for axis in composite_axis if axis_name2known_length[axis] != _unknown_axis_length}
/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/einops/einops.py:317: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unknown: Set[str] = {axis for axis in composite_axis if axis_name2known_length[axis] == _unknown_axis_length}
2024-04-02 21:22:12.595865: Unable to plot network architecture:
2024-04-02 21:22:12.596317: Argument passed to at() was not in the map.
2024-04-02 21:22:12.731663: 
2024-04-02 21:22:12.731911: Epoch 0
2024-04-02 21:22:12.732270: Current learning rate: 0.01
using pin_memory on device 0

**Comment by JunMa11** [comment]
How is the training going?
