### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by OCEANOUXIN** [bowang-lab/U-Mamba#28]
hi, thanks for your excellent work. When I run _nnUNetv2_train 1 3d_fullres all -tr nnUNetTrainerUMambaBot_
![image](https://github.com/bowang-lab/U-Mamba/assets/90253968/46f0cbe5-a599-46b9-8ef6-a17f075cd609)I don't how to solve it.Could you give me some advise?

**Comment by JunMa11** [comment]
Hi @OCEANOUXIN ,

Could you please test whether mamba is successfully installed?

**Comment by LiB98** [comment]
> Hi @OCEANOUXIN ,
> 
> Could you please test whether mamba is successfully installed?

I  encounter this problem too
Requirement already satisfied: mamba-ssm in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (1.2.0.post1)
Requirement already satisfied: triton in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (2.0.0)
Requirement already satisfied: einops in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (0.7.0)
Requirement already satisfied: packaging in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (21.3)
Requirement already satisfied: torch in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (2.0.1)
Requirement already satisfied: transformers in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (4.39.2)
Requirement already satisfied: ninja in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from mamba-ssm) (1.11.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from packaging->mamba-ssm) (3.0.9)
Requirement already satisfied: filelock in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (3.13.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.7.99)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (2.14.3)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (10.2.10.91)
Requirement already satisfied: jinja2 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (3.1.3)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (10.9.0.58)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (8.5.0.96)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.7.101)
Requirement already satisfied: networkx in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (3.2.1)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.4.0.1)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.7.99)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.7.91)
Requirement already satisfied: sympy in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (1.12)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (11.10.3.66)
Requirement already satisfied: typing-extensions in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from torch->mamba-ssm) (4.10.0)
Requirement already satisfied: lit in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from triton->mamba-ssm) (18.1.2)
Requirement already satisfied: cmake in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from triton->mamba-ssm) (3.29.0.1)
Requirement already satisfied: setuptools in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->mamba-ssm) (65.4.0)
Requirement already satisfied: wheel in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->mamba-ssm) (0.37.1)
Requirement already satisfied: requests in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (2.31.0)
Requirement already satisfied: tqdm>=4.27 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (4.66.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (0.22.1)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (0.15.2)
Requirement already satisfied: regex!=2019.12.17 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (2023.12.25)
Requirement already satisfied: safetensors>=0.4.1 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (0.4.2)
Requirement already satisfied: numpy>=1.17 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (1.25.2)
Requirement already satisfied: pyyaml>=5.1 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from transformers->mamba-ssm) (6.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers->mamba-ssm) (2024.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from jinja2->torch->mamba-ssm) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from requests->transformers->mamba-ssm) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from requests->transformers->mamba-ssm) (2022.9.24)
Requirement already satisfied: urllib3<3,>=1.21.1 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from requests->transformers->mamba-ssm) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from requests->transformers->mamba-ssm) (3.6)
Requirement already satisfied: mpmath>=0.19 in /data/Tools/anaconda/envs/test/lib/python3.10/site-packages (from sympy->torch->mamba-ssm) (1.3.0)

**Comment by OCEANOUXIN** [comment]
> Hi @OCEANOUXIN ,
> 
> Could you please test whether mamba is successfully installed?

It likes this 
![image](https://github.com/bowang-lab/U-Mamba/assets/90253968/805a4edd-b924-4c9b-a77d-ad88104f640b)

**Comment by LiB98** [comment]
> > Hi @OCEANOUXIN ,
> > Could you please test whether mamba is successfully installed?
> 
> It likes this ![image](https://private-user-images.githubusercontent.com/90253968/318041118-805a4edd-b924-4c9b-a77d-ad88104f640b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NjUwMzcsIm5iZiI6MTcxMTc2NDczNywicGF0aCI6Ii85MDI1Mzk2OC8zMTgwNDExMTgtODA1YTRlZGQtYjkyNC00YzliLWE3N2QtYWQ4ODEwNGY2NDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGQ1MWY2OWRlMDYwMjk1NzM3MjQyNzZmOTk4YWRkNDM3Yzg4Nzk3ZDY2YTNjNjY2MDE1Yjc2NjJlMDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1iD0Uqdx_MXHkJJ4eCsyimQW7uai8LHNmRj7fGamSg)

I think you should create a new env, and follow the orders that authors show. Maybe you install the mamba_ssm first and change the version of torch, but it is wrong. So  you might reloaded the mamba_ssm (you might need "pip cache refresh") after the downloading the right  torch

**Comment by OCEANOUXIN** [comment]
> > > Hi @OCEANOUXIN ,
> > > Could you please test whether mamba is successfully installed?
> > 
> > 
> > It likes this ![image](https://private-user-images.githubusercontent.com/90253968/318041118-805a4edd-b924-4c9b-a77d-ad88104f640b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NjUwMzcsIm5iZiI6MTcxMTc2NDczNywicGF0aCI6Ii85MDI1Mzk2OC8zMTgwNDExMTgtODA1YTRlZGQtYjkyNC00YzliLWE3N2QtYWQ4ODEwNGY2NDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGQ1MWY2OWRlMDYwMjk1NzM3MjQyNzZmOTk4YWRkNDM3Yzg4Nzk3ZDY2YTNjNjY2MDE1Yjc2NjJlMDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1iD0Uqdx_MXHkJJ4eCsyimQW7uai8LHNmRj7fGamSg)
> 
> I think you should create a new env, and follow the orders that authors show. Maybe you install the mamba_ssm first and change the version of torch, but it is wrong. So you might reloaded the mamba_ssm (you might need "pip cache refresh") after the downloading the right torch.Additionally, the version of mamba_ssm might be the 1.1.4

Hi, I really appreciate your reply.
I try to create a new env as the author shows, but I got this:
![image](https://github.com/bowang-lab/U-Mamba/assets/90253968/bc7df85a-bcde-4a3e-b581-08edb424732f)
The author says the version of  _CUDA 11.7_, my version is ：
![image](https://github.com/bowang-lab/U-Mamba/assets/90253968/8c212f83-4072-4f46-b058-4340dd9822ea)
 Does my version have an impact？Isn't the CUDA12.3 backwards compatible?
Best wishes!

**Comment by LiB98** [comment]
> > > > Hi @OCEANOUXIN ,
> > > > Could you please test whether mamba is successfully installed?
> > > 
> > > 
> > > It likes this ![image](https://private-user-images.githubusercontent.com/90253968/318041118-805a4edd-b924-4c9b-a77d-ad88104f640b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NjUwMzcsIm5iZiI6MTcxMTc2NDczNywicGF0aCI6Ii85MDI1Mzk2OC8zMTgwNDExMTgtODA1YTRlZGQtYjkyNC00YzliLWE3N2QtYWQ4ODEwNGY2NDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGQ1MWY2OWRlMDYwMjk1NzM3MjQyNzZmOTk4YWRkNDM3Yzg4Nzk3ZDY2YTNjNjY2MDE1Yjc2NjJlMDhkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1iD0Uqdx_MXHkJJ4eCsyimQW7uai8LHNmRj7fGamSg)
> > 
> > 
> > I think you should create a new env, and follow the orders that authors show. Maybe you install the mamba_ssm first and change the version of torch, but it is wrong. So you might reloaded the mamba_ssm (you might need "pip cache refresh") after the downloading the right torch.Additionally, the version of mamba_ssm might be the 1.1.4
> 
> Hi, I really appreciate your reply. I try to create a new env as the author shows, but I got this: ![image](https://private-user-images.githubusercontent.com/90253968/318188823-bc7df85a-bcde-4a3e-b581-08edb424732f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTc3MDgsIm5iZiI6MTcxMTc5NzQwOCwicGF0aCI6Ii85MDI1Mzk2OC8zMTgxODg4MjMtYmM3ZGY4NWEtYmNkZS00YTNlLWI1ODEtMDhlZGI0MjQ3MzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDExMTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYjY3YmVjYjcwOGQyNTI0ODZmYjkwYzA1NmI4Y2UyOTY2YzFlYzJkM2MxOTVmN2Y0MTU2Zjk0ZGYzYWZmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gKcfurumNXMVKPBAUgTp0DjpZyf0bB2Y5WYiN-dzkaE) The author says the version of _CUDA 11.7_, my version is ： ![image](https://private-user-images.githubusercontent.com/90253968/318189007-8c212f83-4072-4f46-b058-4340dd9822ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTc3MDgsIm5iZiI6MTcxMTc5NzQwOCwicGF0aCI6Ii85MDI1Mzk2OC8zMTgxODkwMDctOGMyMTJmODMtNDA3Mi00ZjQ2LWIwNTgtNDM0MGRkOTgyMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDExMTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZjQwNjgzMmM4NmJiODU4YTRkY2QyZDlkZDlmZWMwMWU4MWRmYzRhZjkyNDgxMWU0OTE1YjY3ZWU2MzNiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9pCc-S6SQxbMrNoacuo_O0N764Vsejluy1thwDaE6Cw) Does my version have an impact？Isn't the CUDA12.3 backwards compatible? Best wishes!

you can first solve the "error :No module name 'packaging'" using pip install packaging.and try it again. If you can't solve this problem, you'd better to download the version of torch author suggested

**Comment by JunMa11** [comment]
Hi all, 

`pip install causal-conv1d>=1.2.0` can solve this issue!
