### ISSUE TITLE
Predict error

### ISSUE THREAD

**Issue by Sunzechen1219** [bowang-lab/U-Mamba#34]
Hello,I have this error when I predict the image.Why??
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/mnt/workspace/szc/U-mamba/U-Mamba/data/nnUNet_raw/Dataset701_AbdomenCT/imagesVal/._FLARETs_0023_0000.nii.gz"

**Comment by moeinheidari7829** [comment]
> Hello,I have this error when I predict the image.Why?? RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105: sitk::ERROR: Unable to determine ImageIO reader for "/mnt/workspace/szc/U-mamba/U-Mamba/data/nnUNet_raw/Dataset701_AbdomenCT/imagesVal/._FLARETs_0023_0000.nii.gz"

Hi there. Can you please mention how you solved the error? I am facing a similar issue with the inference code.

**Comment by Sunzechen1219** [comment]
> > Hello,I have this error when I predict the image.Why?? RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105: sitk::ERROR: Unable to determine ImageIO reader for "/mnt/workspace/szc/U-mamba/U-Mamba/data/nnUNet_raw/Dataset701_AbdomenCT/imagesVal/._FLARETs_0023_0000.nii.gz"
> 
> Hi there. Can you please mention how you solved the error? I am facing a similar issue with the inference code.


It seems that there are a few redundant erroneous files in the 701 dataset, which can be resolved by deleting them.

**Comment by moeinheidari7829** [comment]
> > > Hello,I have this error when I predict the image.Why?? RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105: sitk::ERROR: Unable to determine ImageIO reader for "/mnt/workspace/szc/U-mamba/U-Mamba/data/nnUNet_raw/Dataset701_AbdomenCT/imagesVal/._FLARETs_0023_0000.nii.gz"
> > 
> > 
> > Hi there. Can you please mention how you solved the error? I am facing a similar issue with the inference code.
> 
> It seems that there are a few redundant erroneous files in the 701 dataset, which can be resolved by deleting them.

Thank you for your reply. can you please tell me which files need to be deleted exactly?

**Comment by Sunzechen1219** [comment]
> > > > Hello,I have this error when I predict the image.Why?? RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105: sitk::ERROR: Unable to determine ImageIO reader for "/mnt/workspace/szc/U-mamba/U-Mamba/data/nnUNet_raw/Dataset701_AbdomenCT/imagesVal/._FLARETs_0023_0000.nii.gz"
> > > 
> > > 
> > > Hi there. Can you please mention how you solved the error? I am facing a similar issue with the inference code.
> > 
> > 
> > It seems that there are a few redundant erroneous files in the 701 dataset, which can be resolved by deleting them.
> 
> Thank you for your reply. can you please tell me which files need to be deleted exactly?


Sorry, this happened a long time ago. However, I remember that the files mentioned in the error messages were deleted, approximately two or three.The images to be deleted had a different format (or possibly naming convention) compared to the other images.
