### ISSUE TITLE
error：nnUNetv2_plan_and_preprocess

### ISSUE THREAD

**Issue by neu-null** [bowang-lab/U-Mamba#4]
Fingerprint extraction...
Traceback (most recent call last):
  File "/root/anaconda3/envs/umamba/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2==2.1.1', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 2. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/data1/dataset/nnUNet_preprocessed
nnUNet_results=/data1/dataset/nnUNet_results
nnUNet_raw=/data1/dataset/nnUNet_raw
If something is not right, adapt your environment variables.

**Comment by neu-null** [comment]
> Fingerprint extraction... Traceback (most recent call last): File "/root/anaconda3/envs/umamba/bin/nnUNetv2_plan_and_preprocess", line 33, in sys.exit(load_entry_point('nnunetv2==2.1.1', 'console_scripts', 'nnUNetv2_plan_and_preprocess')()) File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose) File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean, File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset dataset_name = convert_id_to_dataset_name(dataset_id) File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID " RuntimeError: Could not find a dataset with the ID 2. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders: nnUNet_preprocessed=/data1/dataset/nnUNet_preprocessed nnUNet_results=/data1/dataset/nnUNet_results nnUNet_raw=/data1/dataset/nnUNet_raw If something is not right, adapt your environment variables.

<img width="213" alt="屏幕截图 2024-01-12 103726" src="https://github.com/bowang-lab/U-Mamba/assets/57702752/cdb58a8b-097c-47e3-b156-99a9ed3961c4">

**Comment by JunMa11** [comment]
what command did you use?

could you please share your paths.py as well?

**Comment by mark-joe** [comment]
See the issue I just filed (#5)
