### ISSUE TITLE
下载的数据集中mask，以及得到的验证mask都是全黑的

### ISSUE THREAD

**Issue by Zacharich** [bowang-lab/U-Mamba#41]
![image](https://github.com/bowang-lab/U-Mamba/assets/65930260/ffdf9851-b3c5-4075-b656-227dfd050090)
![image](https://github.com/bowang-lab/U-Mamba/assets/65930260/6fed3400-7ddc-4fe5-a32e-8ac0cd48b060)

**Comment by yanfangHao** [comment]
我是用自己的数据集一归一化再保存全是黑的，然后不归一化又报错

**Comment by yanfangHao** [comment]
我知道这个了，因为他是0-1保存的，你乘个255就都回来了

**Comment by Zacharich** [comment]
> 我知道这个了，因为他是0-1保存的，你乘个255就都回来了

确实乘一下直接ok了，牛蛙

**Comment by yanfangHao** [comment]
你是在自己数据集上跑的么，测试效果怎么样啊，我在自己数据上跑测试效果很不好，真的崩溃😩

**Comment by Zacharich** [comment]
> 你是在自己数据集上跑的么，测试效果怎么样啊，我在自己数据上跑测试效果很不好，真的崩溃😩

我用的是论文里提到的数据集，没用自己的数据集

**Comment by Weixiang-Sun** [comment]
你好，我乘了255之后只有黑白两部分。作者的彩色不同区块是如何实现的？
