### ISSUE TITLE
Standard nnUNet environment variables overwritten

### ISSUE THREAD

**Issue by mark-joe** [bowang-lab/U-Mamba#5]
In my setup the (nnUNetv2) paths.py contain the lines:

base = join(os.sep.join(__file__.split(os.sep)[:-3]), 'data') # or you can set your own path, e.g., base = '/home/user_name/Documents/U-Mamba/data'
nnUNet_raw = join(base, 'nnUNet_raw') # os.environ.get('nnUNet_raw')
nnUNet_preprocessed = join(base, 'nnUNet_preprocessed') # os.environ.get('nnUNet_preprocessed')
nnUNet_results = join(base, 'nnUNet_results') # os.environ.get('nnUNet_results')

where the nnUNet environment variables are ignored and redefined to some subdirectory of the base (code) directory. Took me a while why U-Mamba did not see my data...

**Comment by ff98li** [comment]
Hi,
the paths to directories of datasets and trained model weights in U-Mamba are preset to the codebase's data directory `U-Mamba/data` to avoid conflicting with the environment variables for preexisting nnUNet instances.
An instruction for configuration datasets is provided in [here](https://github.com/bowang-lab/U-Mamba/blob/main/data/README.md); links to the raw datasets and the pretrained weights for inference are also included.
