### ISSUE TITLE
raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "

### ISSUE THREAD

**Issue by ccode-Rookie** [bowang-lab/U-Mamba#50]
I am a rookie in the field of medical image segmentation，I encountered this error when using nnunetV2，Here are the environment variables I have set。
![image](https://github.com/bowang-lab/U-Mamba/assets/174672917/6e7c09ac-06f4-4f5f-b28b-f65cfe0c012f)

And I can read the corresponding folder through instructions
![image](https://github.com/bowang-lab/U-Mamba/assets/174672917/f6baf39f-8586-44cd-a7bc-bdc52ac96095)

And I wrote a Python file that also indicates that I can read the dataset. json file by setting the environment variables
![image](https://github.com/bowang-lab/U-Mamba/assets/174672917/279a6440-c3ee-4d34-a343-f43d6dde1ba5)

How should I solve this problem?I really hope to receive your help！！！thanks！！

**Comment by 15514706615** [comment]
Did you solve this problem, please, and how did you solve it?
