### ISSUE TITLE
Data Output for Inference 

### ISSUE THREAD

**Issue by claycrews2002** [bowang-lab/U-Mamba#7]
When running inference on a trained model, where can I find data results? I see the output images, but is there more that is produced?

**Comment by JunMa11** [comment]
Hi @claycrews2002 ,

What do you mean by `more`? the output folder should contain the segmentation results.

**Comment by claycrews2002** [comment]
@JunMa11 , thank you for your response. I apologize for being unclear.
I was mistaken in my wording with `inference` and meant `validation`. 

Can you explain more about the data given in the `/data/nnUNet_results/Dataset001_BrainTumour/nnUNetTrainerUMambaBot__nnUNetPlans__2d/fold_all/validation/summary.json` file? Mostly referring to the first part of the data. This is showing the results for the training overall? And what is meant by the `1`, `2`, and `3` under `mean`? 

If this is all in your paper and I just need to re-read then I will respectfully accept that as a response.
Thank you for your help!
```
    "foreground_mean": {
        "Dice": 0.817272894544927,
        "FN": 3993.876033057851,
        "FP": 3768.5612947658406,
        "IoU": 0.7175637111114667,
        "TN": 8889798.23278237,
        "TP": 30439.329889807163,
        "n_pred": 34207.891184573,
        "n_ref": 34433.20592286501
    },
    "mean": {
        "1": {
            "Dice": 0.8708903515417461,
            "FN": 6679.113636363636,
            "FP": 6891.987603305785,
            "IoU": 0.7771023521606181,
            "TN": 8856114.857438017,
            "TP": 58314.04132231405,
            "n_pred": 65206.02892561984,
            "n_ref": 64993.15495867769
        },
        "2": {
            "Dice": 0.7358681476456715,
            "FN": 3427.8512396694214,
            "FP": 2582.710743801653,
            "IoU": 0.6144891238104903,
            "TN": 8907376.861570248,
            "TP": 14612.576446280991,
            "n_pred": 17195.287190082643,
            "n_ref": 18040.427685950413
        },
        "3": {
            "Dice": 0.8450601844473633,
            "FN": 1874.6632231404958,
            "FP": 1830.9855371900826,
            "IoU": 0.7610996573632917,
            "TN": 8905902.979338843,
            "TP": 18391.371900826445,
            "n_pred": 20222.35743801653,
            "n_ref": 20266.035123966944
        }
    },
```

**Comment by JunMa11** [comment]
Hi @claycrews2002 ,

Thanks for your interest. 1-3 corresponds to the labels in your dataset.json file.
